In [73]:
import torch
import numpy as np

In [3]:
print(torch.__version__)

torch.cuda.is_available()

1.10.0


False

In [14]:
x = torch.empty(4,4)

print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39]])


In [16]:
y = torch.rand(3,2,2)

print(y)

tensor([[[0.2513, 0.5717],
         [0.9481, 0.2052]],

        [[0.7743, 0.5787],
         [0.0676, 0.1783]],

        [[0.4310, 0.6408],
         [0.5175, 0.6866]]])


In [22]:
c = torch.zeros(2,3,4)

print(c)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [27]:
e = torch.ones(2,3,dtype=torch.int)

print(e)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [29]:
print(x.dtype)

torch.float32


In [31]:
print(y.size())

torch.Size([3, 2, 2])


In [36]:
x = torch.tensor(([2.5,3.6],[4,6]))

print(x.size())

torch.Size([2, 2])


In [40]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)

print(y)

z = x + y
print(z)

zz = torch.sub(x,y)

print(zz)

tensor([[0.0163, 0.8138],
        [0.8628, 0.3619]])
tensor([[0.7566, 0.0875],
        [0.0120, 0.6748]])
tensor([[0.7729, 0.9012],
        [0.8749, 1.0367]])
tensor([[-0.7404,  0.7263],
        [ 0.8508, -0.3130]])


In [67]:
x = torch.rand(3,5)

print(x)

tensor([[0.3449, 0.5166, 0.7169, 0.6062, 0.4652],
        [0.2340, 0.3478, 0.8008, 0.3696, 0.6738],
        [0.2439, 0.4870, 0.3401, 0.3989, 0.1219]])


In [68]:
print((x[1,0].item()))

0.23403054475784302


In [72]:
shape = x.view(-1,15)
print(shape)
print(shape.size())

tensor([[0.3449, 0.5166, 0.7169, 0.6062, 0.4652, 0.2340, 0.3478, 0.8008, 0.3696,
         0.6738, 0.2439, 0.4870, 0.3401, 0.3989, 0.1219]])
torch.Size([1, 15])


In [81]:
a = torch.rand(5)

print(a)
print(type(a))

tensor([0.5003, 0.4407, 0.8853, 0.3201, 0.9513])
<class 'torch.Tensor'>


In [82]:
b = a.numpy()

print(b)
print(type(b))


[0.5003041  0.44073302 0.88534975 0.32009208 0.9512779 ]
<class 'numpy.ndarray'>


In [83]:
torch.add(a,1)

tensor([1.5003, 1.4407, 1.8853, 1.3201, 1.9513])

In [85]:
a.add_(1)

tensor([1.5003, 1.4407, 1.8853, 1.3201, 1.9513])

In [86]:
print(b)

[1.5003041 1.440733  1.8853498 1.3200921 1.951278 ]


In [90]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [91]:
b = torch.from_numpy(a)

In [92]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [2]:
import torch
torch.cuda.is_available()

False

In [14]:
x = torch.rand(3,2, requires_grad=True)

print(x)

tensor([[0.1237, 0.3519],
        [0.7560, 0.9213],
        [0.1121, 0.8220]], requires_grad=True)


In [15]:
y = x + 2

print(y)

z  = y*y*2
z = z.mean()
print(z)

tensor([[2.1237, 2.3519],
        [2.7560, 2.9213],
        [2.1121, 2.8220]], grad_fn=<AddBackward0>)
tensor(12.8652, grad_fn=<MeanBackward0>)


In [16]:
z.backward()
print(x.grad)

tensor([[1.4158, 1.5679],
        [1.8373, 1.9475],
        [1.4081, 1.8813]])
